#### 1. Create a NumPy array 'arr' of integers from 0 to 5 and print its data type.

In [1]:
import numpy as np

arr = np.array([0, 1, 2, 3, 4, 5])
print("Array:", arr)
print("Data Type:", arr.dtype)


Array: [0 1 2 3 4 5]
Data Type: int32


#### 2. Check if a NumPy array's data type is float64.

In [2]:
arr = np.array([1.1, 2.2, 3.3])
print("Is float64:", arr.dtype == np.float64)


Is float64: True


#### 3. Create an array with complex128 data type.

In [3]:
arr = np.array([1+2j, 3+4j, 5+6j], dtype=np.complex128)
print("Array:", arr)
print("Data Type:", arr.dtype)


Array: [1.+2.j 3.+4.j 5.+6.j]
Data Type: complex128


####  4. Convert integer array to float32.

In [4]:
arr = np.array([1, 2, 3, 4])
arr_float = arr.astype(np.float32)
print("Converted Array:", arr_float)
print("Data Type:", arr_float.dtype)


Converted Array: [1. 2. 3. 4.]
Data Type: float32


####  5. Convert float64 to float32 to reduce precision.

In [5]:
arr = np.array([1.1111111111, 2.2222222222, 3.3333333333], dtype=np.float64)
arr_reduced = arr.astype(np.float32)
print("Original:", arr)
print("Reduced Precision:", arr_reduced)


Original: [1.11111111 2.22222222 3.33333333]
Reduced Precision: [1.1111112 2.2222223 3.3333333]


####  6. Write a function array_attributes that takes a NumPy array as input and returns its shape, size, and data type.

In [6]:
def array_attributes(arr):
    return arr.shape, arr.size, arr.dtype

arr = np.array([[1, 2], [3, 4]])
print(array_attributes(arr))


((2, 2), 4, dtype('int32'))


####  7. Create a function array_dimension that takes a NumPy array as input and returns its dimensionality.

In [7]:
def array_dimension(arr):
    return arr.ndim

arr = np.array([[1, 2, 3], [4, 5, 6]])
print(array_dimension(arr))


2


#### 8. Design a function item_size_info that takes a NumPy array as input and returns the item size and the total size in bytes.
 


In [8]:
def item_size_info(arr):
    return arr.itemsize, arr.nbytes

arr = np.array([[10, 20], [30, 40]])
print(item_size_info(arr))


(4, 16)


 #### 9. Create a function array_strides that takes a NumPy array as input and returns the strides of the array.

In [9]:
def array_strides(arr):
    return arr.strides

arr = np.array([1.5, 2.6, 3.7])
print(array_strides(arr))


(8,)


#### 10. Design a function shape_stride_relationship that takes a NumPy array as input and returns the shape and strides of the array.
 


In [11]:
def shape_stride_relationship(arr):
    return arr.shape, arr.strides

arr = np.array([[1, 2], [3, 4]])
print(shape_stride_relationship(arr))


((2, 2), (8, 4))


#### 11. Create a function create_zeros_array that takes an integer n as input and returns a NumPy array of zeros with n elements.

In [12]:
def create_zeros_array(n):
    return np.zeros(n)

print(create_zeros_array(5))


[0. 0. 0. 0. 0.]


####  12. Write a function create_ones_matrix that takes integers rows and cols as inputs and generates a 2D NumPy array filled with ones of size rows x cols.

In [13]:
def create_ones_matrix(rows, cols):
    return np.ones((rows, cols))

print(create_ones_matrix(3, 4))


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


####  13. Write a function generate_range_array that takes three integers start, stop, and step as arguments and creates a NumPy array with a range starting from start, ending at stop (exclusive), and with the specified step.

In [14]:
def generate_range_array(start, stop, step):
    return np.arange(start, stop, step)

print(generate_range_array(2, 10, 2))


[2 4 6 8]


#### 14. Design a function generate_linear_space that takes two floats start, stop, and an integer num as arguments and generates a NumPy array with num equally spaced values between start and stop (inclusive).

In [15]:
def generate_linear_space(start, stop, num):
    return np.linspace(start, stop, num)

print(generate_linear_space(0, 1, 5))


[0.   0.25 0.5  0.75 1.  ]


#### 15. Create a function create_identity_matrix that takes an integer n as input and generates a square identity matrix of size n x n using numpy.eye.

In [16]:
def create_identity_matrix(n):
    return np.eye(n)

print(create_identity_matrix(3))


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 16. Write a function that takes a Python list and converts it into a NumPy array.
 


In [17]:
def list_to_array(lst):
    return np.array(lst)

print(list_to_array([1, 2, 3, 4]))


[1 2 3 4]


#### 17. Create a NumPy array and demonstrate the use of numpy.view to create a new array object with the same data.

In [18]:
arr = np.array([1, 2, 3, 4])
view_arr = arr.view()

print("Original:", arr)
print("View:", view_arr)


Original: [1 2 3 4]
View: [1 2 3 4]


#### 18. Write a function that takes two NumPy arrays and concatenates them along a specified axis.

In [19]:
def concat_arrays(a, b, axis=0):
    return np.concatenate((a, b), axis=axis)

a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
print(concat_arrays(a, b, axis=0))


[[1 2]
 [3 4]
 [5 6]
 [7 8]]


#### 19. Create two NumPy arrays with different shapes and concatenate them horizontally using numpy.concatenate.m

In [21]:
a = np.array([[1], [2], [3]])
b = np.array([[4, 5], [6, 7], [8, 9]])
result = np.concatenate((a, b), axis=1)
print(result)


[[1 4 5]
 [2 6 7]
 [3 8 9]]


####  20. Write a function that vertically stacks multiple NumPy arrays given as a list.
 


In [22]:
def vertical_stack(arrays):
    return np.vstack(arrays)

arr1 = np.array([1, 2])
arr2 = np.array([3, 4])
print(vertical_stack([arr1, arr2]))


[[1 2]
 [3 4]]


#### 21. Write a Python function using NumPy to create an array of integers within a specified range (inclusive) with a given step size.

In [23]:
def create_range_array(start, stop, step):
    return np.arange(start, stop + 1, step)

print(create_range_array(1, 10, 2))


[1 3 5 7 9]


#### 22. Write a Python function using NumPy to generate an array of 10 equally spaced values between 0 and 1 (inclusive).

In [24]:
def equally_spaced():
    return np.linspace(0, 1, 10)

print(equally_spaced())


[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


####  23. Write a Python function using NumPy to create an array of 5 logarithmically spaced values between 1 and 1000 (inclusive).

In [25]:
def log_spaced_array():
    return np.logspace(0, 3, 5)

print(log_spaced_array())


[   1.            5.62341325   31.6227766   177.827941   1000.        ]


#### 24. Create a Pandas DataFrame using a NumPy array that contains 5 rows and 3 columns, where the values are random integers between 1 and 100.
 


In [27]:
import pandas as pd

data = np.random.randint(1, 101, size=(5, 3))
df = pd.DataFrame(data, columns=["A", "B", "C"])
print(df)


     A   B   C
0   94  86  45
1   89   1  12
2  100  16  16
3   75   3  93
4   71  62  80


#### 25. Write a function that takes a Pandas DataFrame and replaces all negative values in a specific column with zeros. Use NumPy operations within the Pandas DataFrame.

In [28]:
def replace_negatives(df, column):
    df[column] = np.where(df[column] < 0, 0, df[column])
    return df

df = pd.DataFrame({'val': [10, -5, 20, -3]})
print(replace_negatives(df, 'val'))


   val
0   10
1    0
2   20
3    0


####  26. Access the 3rd element from the given NumPy array.

In [29]:
arr = np.array([10, 20, 30, 40, 50])
print(arr[2])

30


####  27. Retrieve the element at index (1, 2) from the 2D NumPy array.

In [30]:
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])
print(arr[1, 2])


6


#### 28. Using boolean indexing, extract elements greater than 5 from the given NumPy array.

In [31]:
arr = np.array([3, 8, 2, 10, 5, 7])
print(arr[arr > 5])


[ 8 10  7]


####  29. Perform basic slicing to extract elements from index 2 to 5 (inclusive) from the given NumPy array.
 


In [32]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
print(arr[2:6])


[3 4 5 6]


#### 30. Slice the 2D NumPy array to extract the sub-array [[2, 3], [5, 6]] from the given array.

In [33]:
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
sub_array = arr_2d[0:2, 1:3]
print(sub_array)


[[2 3]
 [5 6]]


####  31. Write a NumPy function to extract elements in specific order from a given 2D array based on indices provided in another array.

In [34]:
def extract_elements_with_indices(arr, indices):
    return arr[tuple(indices.T)]

arr = np.array([[10, 20, 30],
                [40, 50, 60],
                [70, 80, 90]])

indices = np.array([[0, 1], [1, 2], [2, 0]])  # Extract: 20, 60, 70
print(extract_elements_with_indices(arr, indices))


[20 60 70]


#### 32. Create a NumPy function that filters elements greater than a threshold from a given 1D array using boolean indexing.
 


In [35]:
def filter_greater_than(arr, threshold):
    return arr[arr > threshold]

arr = np.array([3, 8, 1, 10, 5])
print(filter_greater_than(arr, 5))


[ 8 10]


#### 33. Develop a NumPy function that extracts specific elements from a 3D array using indices provided in three separate arrays for each dimension.
 

In [36]:
def extract_from_3d(arr, x_idx, y_idx, z_idx):
    return arr[x_idx, y_idx, z_idx]

arr = np.arange(27).reshape(3, 3, 3)
x = np.array([0, 1, 2])
y = np.array([1, 1, 1])
z = np.array([2, 0, 1])

print(extract_from_3d(arr, x, y, z))


[ 5 12 22]


#### 34. Write a NumPy function that returns elements from an array where both two conditions are satisfied using boolean indexing.
 


In [37]:
def filter_multiple_conditions(arr):
    return arr[(arr > 10) & (arr % 2 == 0)]

arr = np.array([5, 12, 17, 8, 24, 3])
print(filter_multiple_conditions(arr))


[12 24]


####  35. Create a NumPy function that extracts elements from a 2D array using row and column indices provided in separate arrays.

In [38]:
def extract_with_row_col(arr, row_idx, col_idx):
    return arr[row_idx, col_idx]

arr = np.array([[10, 20, 30],
                [40, 50, 60],
                [70, 80, 90]])

rows = np.array([0, 1, 2])
cols = np.array([2, 1, 0])

print(extract_with_row_col(arr, rows, cols))  # 30, 50, 70


[30 50 70]


#### 36. Given an array arr of shape (3, 3), add a scalar value of 5 to each element using NumPy broadcasting.

In [39]:
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

arr_added = arr + 5
print(arr_added)


[[ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


####  37. Consider two arrays arr1 of shape (1, 3) and arr2 of shape (3, 4). Multiply each row of arr2 by the corresponding element in arr1 using NumPy broadcasting.

In [40]:
arr1 = np.array([[2, 3, 4]])  # shape (1,3)
arr2 = np.array([[1, 2, 3, 4],
                 [5, 6, 7, 8],
                 [9,10,11,12]])  # shape (3,4)

# Transpose arr1 for broadcasting
result = arr2 * arr1.T
print(result)


[[ 2  4  6  8]
 [15 18 21 24]
 [36 40 44 48]]


####  38. Given a 1D array arr1 of shape (1, 4) and a 2D array arr2 of shape (4, 3), add arr1 to each row of arr2 using NumPy broadcasting.

In [41]:
arr1 = np.array([[1, 2, 3, 4]])  # (1, 4)
arr2 = np.array([[5], [6], [7], [8]])  # (4,1)

result = arr1 + arr2  # Shape (4,4)
print(result)


[[ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]]


#### 39. Consider two arrays arr1 of shape (3, 1) and arr2 of shape (1, 3). Add these arrays using NumPy broadcasting.

In [42]:
arr1 = np.array([[1], [2], [3]])  # shape (3,1)
arr2 = np.array([[4, 5, 6]])      # shape (1,3)

result = arr1 + arr2
print(result)


[[5 6 7]
 [6 7 8]
 [7 8 9]]


#### 40. Given arrays arr1 of shape (2, 3) and arr2 of shape (2, 2), perform multiplication using NumPy broadcasting. Handle the shape incompatibility.
 

In [43]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])  # shape (2, 3)
arr2 = np.array([[1, 2], [3, 4]])       # shape (2, 2)

try:
    result = arr1 * arr2
    print(result)
except ValueError as e:
    print("Error:", e)


Error: operands could not be broadcast together with shapes (2,3) (2,2) 


#### 41. Calculate column-wise mean for the given array:
 

In [44]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
column_mean = np.mean(arr, axis=0)
print("Column-wise Mean:", column_mean)


Column-wise Mean: [2.5 3.5 4.5]


#### 42. Find maximum value in each row of the given array:

In [45]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
row_max = np.max(arr, axis=1)
print("Max in each row:", row_max)


Max in each row: [3 6]


####  43. For the given array, find indices of maximum value in each column:
 


In [46]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
max_indices = np.argmax(arr, axis=0)
print("Indices of max in each column:", max_indices)


Indices of max in each column: [1 1 1]


#### 44. For the given array, apply custom function to calculate moving sum along rows:

In [48]:
def moving_sum(arr):
    return np.cumsum(arr, axis=1)

arr = np.array([[1, 2, 3], [4, 5, 6]])
print("Moving sum along rows:\n", moving_sum(arr))


Moving sum along rows:
 [[ 1  3  6]
 [ 4  9 15]]


#### 45. In the given array, check if all elements in each column are even.

In [49]:
arr = np.array([[2, 4, 6], [3, 5, 7]])
all_even = np.all(arr % 2 == 0, axis=0)
print("All elements even in each column:", all_even)


All elements even in each column: [False False False]


#### 46. Given a NumPy array arr, reshape it into a matrix of dimensions m rows and n columns. Return the reshaped matrix.
 

In [50]:
def reshape_array(arr, m, n):
    return arr.reshape((m, n))

arr = np.array([1, 2, 3, 4, 5, 6])
print(reshape_array(arr, 2, 3))


[[1 2 3]
 [4 5 6]]


#### 47. Create a function that takes a matrix as input and returns the flattened array.

In [51]:
def flatten_matrix(matrix):
    return matrix.flatten()

matrix = np.array([[1, 2], [3, 4]])
print(flatten_matrix(matrix))


[1 2 3 4]


#### 48. Write a function that concatenates two given arrays along a specified axis.
 


In [52]:
def concatenate_arrays(arr1, arr2, axis):
    return np.concatenate((arr1, arr2), axis=axis)

arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
print(concatenate_arrays(arr1, arr2, axis=0))


[[1 2]
 [3 4]
 [5 6]
 [7 8]]


#### 49. Create a function that splits an array into multiple sub-arrays along a specified axis.

In [53]:
def split_array(arr, sections, axis):
    return np.array_split(arr, sections, axis=axis)

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
splits = split_array(arr, 2, axis=1)
for i, s in enumerate(splits):
    print(f"Split {i+1}:\n", s)


Split 1:
 [[1 2]
 [5 6]]
Split 2:
 [[3 4]
 [7 8]]


####  50. Write a function that inserts and then deletes elements from a given array at specified indices.
 

In [54]:
def insert_and_delete(arr, insert_indices, insert_values, delete_indices):
    arr = np.insert(arr, insert_indices, insert_values)
    arr = np.delete(arr, delete_indices)
    return arr

original_array = np.array([1, 2, 3, 4, 5])
insert_indices = [2, 4]
insert_values = [10, 11]
delete_indices = [1, 3]
print(insert_and_delete(original_array, insert_indices, insert_values, delete_indices))


[ 1 10  4 11  5]


#### 51. Create a NumPy array arr1 with random integers and another array arr2 with integers from 1 to 10. Perform element-wise addition between arr1 and arr2.

In [55]:
arr1 = np.random.randint(1, 50, size=10)
arr2 = np.arange(1, 11)
result = arr1 + arr2
print("arr1:", arr1)
print("arr2:", arr2)
print("Sum:", result)


arr1: [48  3 44 15 37 45 28 30 46 18]
arr2: [ 1  2  3  4  5  6  7  8  9 10]
Sum: [49  5 47 19 42 51 35 38 55 28]


####  52. Generate a NumPy array arr1 with sequential integers from 10 to 1 and another array arr2 with integers from 1 to 10. Subtract arr2 from arr1 element-wise.

In [56]:
arr1 = np.arange(10, 0, -1)
arr2 = np.arange(1, 11)
result = arr1 - arr2
print("Subtraction:", result)


Subtraction: [ 9  7  5  3  1 -1 -3 -5 -7 -9]


#### 53. Create a NumPy array arr1 with random integers and another array arr2 with integers from 1 to 5. Perform element-wise multiplication between arr1 and arr2.
 


In [57]:
arr1 = np.random.randint(1, 10, size=5)
arr2 = np.arange(1, 6)
result = arr1 * arr2
print("Multiplication:", result)


Multiplication: [ 9 16 15 16 25]


####  54. Generate a NumPy array arr1 with even integers from 2 to 10 and another array arr2 with integers from 1 to 5. Perform element-wise division of arr1 by arr2.

In [58]:
arr1 = np.arange(2, 11, 2)  # [2, 4, 6, 8, 10]
arr2 = np.arange(1, 6)
result = arr1 / arr2
print("Division:", result)


Division: [2. 2. 2. 2. 2.]


#### 55. Create a NumPy array arr1 with integers from 1 to 5 and another array arr2 with the same numbers reversed. Calculate the exponentiation of arr1 raised to the power of arr2 element-wise.

In [59]:
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = arr1[::-1]
result = arr1 ** arr2
print("Exponentiation:", result)


Exponentiation: [ 1 16 27 16  5]


####  56. Write a function that counts the occurrences of a specific substring within a NumPy array of strings.

In [60]:
def count_substring(arr, substring):
    return np.char.count(arr, substring).sum()

arr = np.array(['hello', 'world', 'hello', 'numpy', 'hello'])
print("Count:", count_substring(arr, 'hello'))


Count: 3


####  57. Write a function that extracts uppercase characters from a NumPy array of strings.

In [61]:
def extract_uppercase(arr):
    return [ ''.join(filter(str.isupper, word)) for word in arr ]

arr = np.array(['Hello', 'World', 'OpenAI', 'GPT'])
print("Uppercase characters:", extract_uppercase(arr))


Uppercase characters: ['H', 'W', 'OAI', 'GPT']


#### 58. Write a function that replaces occurrences of a substring in a NumPy array of strings with a new string.

In [62]:
def replace_substring(arr, old, new):
    return np.char.replace(arr, old, new)

arr = np.array(['apple', 'banana', 'grape', 'pineapple'])
print(replace_substring(arr, 'apple', 'fruit'))


['fruit' 'banana' 'grape' 'pinefruit']


#### 59. Write a function that concatenates strings in a NumPy array element-wise.

In [63]:
def concat_strings(arr1, arr2):
    return np.char.add(arr1, arr2)

arr1 = np.array(['Hello', 'World'])
arr2 = np.array(['Open', 'AI'])
print(concat_strings(arr1, arr2))


['HelloOpen' 'WorldAI']


#### 60. Write a function that finds the length of the longest string in a NumPy array.
 

In [64]:
def max_string_length(arr):
    return max(np.char.str_len(arr))

arr = np.array(['apple', 'banana', 'grape', 'pineapple'])
print("Max length:", max_string_length(arr))


Max length: 9


#### 61. Create a dataset of 100 random integers between 1 and 1000. Compute the mean, median, variance, and standard deviation using NumPy's functions.

In [65]:
arr = np.random.randint(1, 1001, size=100)
print("Mean:", np.mean(arr))
print("Median:", np.median(arr))
print("Variance:", np.var(arr))
print("Std Dev:", np.std(arr))


Mean: 523.55
Median: 584.0
Variance: 88176.0675
Std Dev: 296.94455290508364


####  62. Generate an array of 50 random numbers between 1 and 100. Find the 25th and 75th percentiles of the dataset.

In [66]:
arr = np.random.randint(1, 101, size=50)
print("25th percentile:", np.percentile(arr, 25))
print("75th percentile:", np.percentile(arr, 75))


25th percentile: 24.25
75th percentile: 78.75


####  63. Create two arrays representing two sets of variables. Compute the correlation coefficient between these arrays using NumPy's corrcoef function.

In [67]:
x = np.random.randint(1, 100, size=10)
y = np.random.randint(1, 100, size=10)
corr = np.corrcoef(x, y)
print("Correlation coefficient matrix:\n", corr)


Correlation coefficient matrix:
 [[ 1.         -0.15973818]
 [-0.15973818  1.        ]]


####  64. Create two matrices and perform matrix multiplication using NumPy's dot function.

In [68]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
result = np.dot(A, B)
print("Matrix multiplication result:\n", result)


Matrix multiplication result:
 [[19 22]
 [43 50]]


####  65. Create an array of 50 integers between 10 and 1000. Calculate the 10th, 50th (median), and 90th percentiles along with the first and third quartiles.

In [69]:
arr = np.random.randint(10, 1001, size=50)
print("10th percentile:", np.percentile(arr, 10))
print("25th percentile (Q1):", np.percentile(arr, 25))
print("50th percentile (median):", np.percentile(arr, 50))
print("75th percentile (Q3):", np.percentile(arr, 75))
print("90th percentile:", np.percentile(arr, 90))


10th percentile: 173.6
25th percentile (Q1): 349.25
50th percentile (median): 530.5
75th percentile (Q3): 776.25
90th percentile: 862.4


#### 66. Create a NumPy array of integers and find the index of a specific element.
 

In [70]:
arr = np.array([10, 20, 30, 40, 50])
index = np.where(arr == 30)[0][0]
print("Index of 30:", index)


Index of 30: 2


#### 67. Generate a random NumPy array and sort it in ascending order.

In [71]:
arr = np.random.randint(1, 100, size=10)
sorted_arr = np.sort(arr)
print("Sorted array:", sorted_arr)


Sorted array: [ 3  7 17 28 30 44 52 90 94 98]


####  68. Filter elements > 20 in the given NumPy array.

In [72]:
arr = np.array([12, 25, 6, 42, 8, 30])
filtered = arr[arr > 20]
print("Elements > 20:", filtered)


Elements > 20: [25 42 30]


#### 69. Filter elements which are divisible by 3 from a given NumPy array.

In [73]:
arr = np.array([1, 5, 8, 12, 15])
filtered = arr[arr % 3 == 0]
print("Divisible by 3:", filtered)


Divisible by 3: [12 15]


####  70. Filter elements which are ≥ 20 and ≤ 40 from a given NumPy array.

In [74]:
arr = np.array([10, 20, 30, 40, 50])
filtered = arr[(arr >= 20) & (arr <= 40)]
print("Between 20 and 40:", filtered)


Between 20 and 40: [20 30 40]


#### 71. For the given NumPy array, check its byte order using the dtype attribute byteorder.

In [75]:
arr = np.array([1, 2, 3], dtype=np.int32)
print("Byte order:", arr.dtype.byteorder)


Byte order: =


####  72. For the given NumPy array, perform byte swapping in place using byteswap().

In [76]:
arr = np.array([1, 2, 3], dtype=np.int32)
arr.byteswap(inplace=True)
print("After byte swap:", arr)


After byte swap: [16777216 33554432 50331648]


#### 73. For the given NumPy array, swap its byte order without modifying the original array using newbyteorder().

In [77]:
arr = np.array([1, 2, 3], dtype=np.int32)
swapped = arr.newbyteorder()
print("Original:", arr)
print("New Byte Order:", swapped)


Original: [1 2 3]
New Byte Order: [16777216 33554432 50331648]


####  74. For the given NumPy array, swap its byte order conditionally based on system endianness using newbyteorder().

In [78]:
arr = np.array([1, 2, 3], dtype=np.int32)
if arr.dtype.byteorder in ('=', '<'):
    swapped = arr.newbyteorder()
    print("Swapped for endianness:", swapped)
else:
    print("No swap needed.")


Swapped for endianness: [16777216 33554432 50331648]


####  75. For the given NumPy array, check if byte swapping is necessary for the current system using dtype attribute byteorder.

In [79]:
arr = np.array([1, 2, 3], dtype=np.int32)
need_swap = arr.dtype.byteorder not in ('=', '|')
print("Byte swap needed:", need_swap)


Byte swap needed: False


####  76. Create a NumPy array arr1 with values from 1 to 10. Create a copy of arr1 named copy_arr and modify an element in copy_arr. Check if modifying copy_arr affects arr1.

In [80]:
arr1 = np.arange(1, 11)
copy_arr = arr1.copy()
copy_arr[0] = 100
print("arr1:", arr1)
print("copy_arr:", copy_arr)


arr1: [ 1  2  3  4  5  6  7  8  9 10]
copy_arr: [100   2   3   4   5   6   7   8   9  10]


####  77. Create a 2D NumPy array matrix of shape (3, 3) with random integers. Extract a slice view_slice from the matrix. Modify an element in view_slice and observe if it changes the original matrix.

In [81]:
matrix = np.random.randint(1, 10, (3, 3))
view_slice = matrix[0:2, 0:2]
view_slice[0, 0] = 99
print("Modified slice:\n", view_slice)
print("Original matrix:\n", matrix)


Modified slice:
 [[99  4]
 [ 1  7]]
Original matrix:
 [[99  4  7]
 [ 1  7  6]
 [ 9  8  5]]


#### 78. Create a NumPy array array_a of shape (4, 3) with sequential integers from 1 to 12. Extract a slice view_b from array_a and broadcast the addition of 5 to view_b. Check if it alters the original array_a.

In [83]:
array_a = np.arange(1, 13).reshape(4, 3)
view_b = array_a[:2, :]
view_b += 5
print("Modified slice:\n", view_b)
print("Original array:\n", array_a)


Modified slice:
 [[ 6  7  8]
 [ 9 10 11]]
Original array:
 [[ 6  7  8]
 [ 9 10 11]
 [ 7  8  9]
 [10 11 12]]


####  79. Create a NumPy array orig_array of shape (2, 4) with values from 1 to 8. Create a reshaped view reshaped_view of shape (4, 2) from orig_array. Modify an element in reshaped_view and check if it reflects changes in the original orig_array.

In [85]:
orig_array = np.arange(1, 9).reshape(2, 4)
reshaped_view = orig_array.reshape(4, 2)
reshaped_view[0, 0] = 99
print("Original array:\n", orig_array)
print("Reshaped view:\n", reshaped_view)


Original array:
 [[99  2  3  4]
 [ 5  6  7  8]]
Reshaped view:
 [[99  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]]


##### 80. Create a NumPy array data of shape (3, 4) with random integers. Extract a copy data_copy of elements greater than 5. Modify an element in data_copy and verify if it affects the original data.

In [86]:
data = np.random.randint(1, 10, (3, 4))
data_copy = data[data > 5].copy()
data_copy[0] = 99
print("Original data:\n", data)
print("Modified copy:", data_copy)


Original data:
 [[9 7 8 2]
 [2 1 4 1]
 [1 8 7 4]]
Modified copy: [99  7  8  8  7]


##### 81. Create two matrices A and B of identical shape containing integers and perform addition and subtraction operations between them.

In [87]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
print("Addition:\n", A + B)
print("Subtraction:\n", A - B)


Addition:
 [[ 6  8]
 [10 12]]
Subtraction:
 [[-4 -4]
 [-4 -4]]


#### 82. Generate two matrices C (3x2) and D (2x4) and perform matrix multiplication.

In [88]:
C = np.array([[1, 2], [3, 4], [5, 6]])
D = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
result = np.dot(C, D)
print("Matrix Multiplication:\n", result)


Matrix Multiplication:
 [[11 14 17 20]
 [23 30 37 44]
 [35 46 57 68]]


#### 83. Create a matrix E and find its transpose.

In [89]:
E = np.array([[1, 2, 3], [4, 5, 6]])
print("Transpose:\n", E.T)


Transpose:
 [[1 4]
 [2 5]
 [3 6]]


####  84. Generate a square matrix F and compute its determinant.

In [90]:
F = np.array([[1, 2], [3, 4]])
det = np.linalg.det(F)
print("Determinant:", det)


Determinant: -2.0000000000000004


#### 85. Create a square matrix G and find its inverse.

In [91]:
G = np.array([[1, 2], [3, 4]])
inverse_G = np.linalg.inv(G)
print("Inverse:\n", inverse_G)


Inverse:
 [[-2.   1. ]
 [ 1.5 -0.5]]
